<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-21T14:53:09 PST" name="Suite" finished-at="2022-11-21T14:53:12 PST" duration-ms="2848">
    <groups>
      <group name="Regression">
        <method signature="TC_15_TestDependency.testMethod1()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" name="testMethod1" class="tests.TC_15_TestDependency"/>
      </group> <!-- Regression -->
      <group name="functest">
        <method signature="TC_15_TestDependency.testMethod2()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" name="testMethod2" class="tests.TC_15_TestDependency"/>
      </group> <!-- functest -->
      <group name="Smoke">
        <method signature="TC_15_TestDependency.testMethod3()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" name="testMethod3" class="tests.TC_15_TestDependency"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2022-11-21T14:53:09 PST" name="Test" finished-at="2022-11-21T14:53:12 PST" duration-ms="2848">
      <class name="tests.TC_15_TestDependency">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" started-at="2022-11-21T14:53:09 PST" name="beforeTest" finished-at="2022-11-21T14:53:12 PST" duration-ms="2567" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="testMethod1()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" started-at="2022-11-21T14:53:12 PST" name="testMethod1" finished-at="2022-11-21T14:53:12 PST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method signature="testMethod2()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" started-at="2022-11-21T14:53:12 PST" name="testMethod2" finished-at="2022-11-21T14:53:12 PST" duration-ms="15" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at tests.TC_15_TestDependency.testMethod2(TC_15_TestDependency.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method signature="testMethod3()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" started-at="2022-11-21T14:53:12 PST" name="testMethod3" depends-on-groups="functest" finished-at="2022-11-21T14:53:12 PST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_15_TestDependency.testMethod3()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41] depends on not successfully finished methods in group "functest"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_15_TestDependency.testMethod3()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41] depends on not successfully finished methods in group "functest"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method signature="testMethod4()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" started-at="2022-11-21T14:53:12 PST" name="testMethod4" depends-on-groups="Smoke" finished-at="2022-11-21T14:53:12 PST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_15_TestDependency.testMethod4()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41] depends on not successfully finished methods in group "Smoke"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_15_TestDependency.testMethod4()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41] depends on not successfully finished methods in group "Smoke"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod4 -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:tests.TC_15_TestDependency@3ce3db41]" started-at="2022-11-21T14:53:12 PST" name="afterTest" finished-at="2022-11-21T14:53:12 PST" duration-ms="170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- tests.TC_15_TestDependency -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
